### ISSUE TITLE
some tests are failing

### ISSUE THREAD

**Issue by ignatenkobrain** [sunng87/handlebars-rust#165]
```
---- helpers::helper_each::test::test_empty_key stdout ----
	thread 'helpers::helper_each::test::test_empty_key' panicked at 'assertion failed: `(left == right)` (left: `["", "-", "foo-bar"]`, right: `["", "-baz", "foo-bar"]`)', src/helpers/helper_each.rs:240
note: Run with `RUST_BACKTRACE=1` for a backtrace.

---- render::test_render_error_line_no stdout ----
	thread 'render::test_render_error_line_no' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:329

---- template::test_whitespace_elements stdout ----
	thread 'template::test_whitespace_elements' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:329
```

Not sure which information I can give more..

**Comment by ignatenkobrain** [comment]
hmm, looks like it is broken due to #164

**Comment by sunng87** [comment]
Yes. Currently we cannot update to pest 0.4. More information is tracked in #117
