### ISSUE TITLE
Skipping unknown variables while rendering template

### ISSUE THREAD

**Issue by Relrin** [sunng87/handlebars-rust#293]
I'm writing an application that handles user's templates and initializes the new project based on the specified templates via CLI commands. However, sometime developers could specify their own templates which could contain their own definitions with variables in curly bracers (e.g. Helm charts use the Mustache template engine for handling user's input). 

So, based on this I have a question related to rendering templates for this case: Is it possible to ignore template rendering errors which caused by missing variables / helpers? 
Currently, for the example listed in the bottom, I'm receiving the following error:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: TemplateRender(RenderError(RenderError { desc: "Helper not defined: Name(\".\")", template_name: None, line_no: Some(82), column_no: Some(45), cause: None }), "test-proj/MakefileCommon")', src/libcore/result.rs:999:5
```

For example, if I have a simple template for generating my own Makefile, like this:
 ```
tag:
            docker tag $(shell docker images --format="{{.Repository}} {{.ID}}" |  grep "{{ project_name }}-$(service)"
``` 
Then pass a context in handlebars instances, so that the passed context has information only for the `project_name` variable and Handlebars will return to the enduser file with the following result:
 ```
tag:
            docker tag $(shell docker images --format="{{.Repository}} {{.ID}}" |  grep "new-project-$(service)"
```

**Comment by sunng87** [comment]
Hi @Relrin , can you use the [raw block](https://handlebars-draft.knappi.org/guide/block-helpers.html#raw-blocks) to wrap the content which may have raw bracers that were not intended to be parsed? 

For handlebars, the dot in bracers are parsed as helper name, so the renderer cannot deal with it.

**Comment by Relrin** [comment]
> can you use the raw block to wrap the content which may have raw bracers that were not intended to be parsed?

In general its possible to wrap each unused manually (and in code as well). However this trick will require to use regular expressions for each pass through the template that could contain unexpected/missing context data. 
Will it work for the case if the template contains more than 2 curly bracers from both sides? (e.g. `{{{{ Helm-Chart-Variable }}}`?

> For handlebars, the dot in bracers are parsed as helper name, so the renderer cannot deal with it.

Does handlebars have any hooks/callbacks for intercepting the behaviour like in this case? Is it possible to register a helper, so that it will skip any "triggered" helper case (the variables started with the dot)?

**Comment by Relrin** [comment]
Any ideas how to avoid panics for the cases, when the handlebars faces with shell variables in files like this: `DOCKER_IMAGE:=$(shell echo $(SOME_VARIABLE)`?

**Comment by sunng87** [comment]
> Does handlebars have any hooks/callbacks for intercepting the behaviour like in this case? Is it possible to register a helper, so that it will skip any "triggered" helper case (the variables started with the dot)?

Actually there is meta helpers called `helperMissing` for undefined inline helper and `helperBlockMissing` for block helper. You just define these two helpers and it should work for you .

> Any ideas how to avoid panics for the cases, when the handlebars faces with shell variables in files like this DOCKER_IMAGE:=$(shell echo $(SOME_VARIABLE) and YAML files with \nor \t symbols.

Could you please show me the backtrace for this panic?

**Comment by Relrin** [comment]
> Could you please show me the backtrace for this panic?
Sure. I'm getting panic in the case, when I do unwrap the result, but Handlebars can't handle some symbols in the template.

```
=> cargo run -- init template multi-service-template
    Finished dev [unoptimized + debuginfo] target(s) in 0.06s
     Running `target/debug/quickproj init template multi-service-template`
⠁ [00:00:00] [######################################################################################################################################] Initializing...
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: TemplateRender(TemplateError(TemplateError { reason: InvalidSyntax, template_name: None, line_no: Some(63), column_no: Some(1), segment: Some("  60 |          probes:\n  61 |             - curl -s -f  \"http://localhost:3000/healthcheck/\"\n") }), "template/test/git-hub-action.yaml")', src/libcore/result.rs:999:5
```
The backtrace:
```
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /Users/vsts/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /Users/vsts/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:214
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:384
   8: rust_begin_unwind
             at src/libstd/panicking.rs:311
   9: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  10: core::result::unwrap_failed
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/macros.rs:18
  11: core::result::Result<T,E>::unwrap
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/result.rs:800
  12: quickproj::templates::task::Task::create_files_from_templates::{{closure}}::{{closure}}
             at src/templates/task.rs:247
  13: core::iter::traits::iterator::Iterator::for_each::{{closure}}
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/iter/traits/iterator.rs:604
  14: core::iter::traits::iterator::Iterator::fold::{{closure}}
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/iter/traits/iterator.rs:1685
  15: core::iter::traits::iterator::Iterator::try_fold
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/iter/traits/iterator.rs:1573
  16: core::iter::traits::iterator::Iterator::fold
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/iter/traits/iterator.rs:1685
  17: core::iter::traits::iterator::Iterator::for_each
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/iter/traits/iterator.rs:604
  18: quickproj::templates::task::Task::create_files_from_templates::{{closure}}
             at src/templates/task.rs:244
  19: core::iter::traits::iterator::Iterator::for_each::{{closure}}
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/iter/traits/iterator.rs:604
  20: core::iter::traits::iterator::Iterator::fold::{{closure}}
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/iter/traits/iterator.rs:1685
  21: core::iter::traits::iterator::Iterator::try_fold
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/iter/traits/iterator.rs:1573
  22: core::iter::traits::iterator::Iterator::fold
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/iter/traits/iterator.rs:1685
  23: core::iter::traits::iterator::Iterator::for_each
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/iter/traits/iterator.rs:604
  24: quickproj::templates::task::Task::create_files_from_templates
             at src/templates/task.rs:200
  25: quickproj::templates::task::Task::run
             at src/templates/task.rs:71
  26: quickproj::templates::handler::Handler::init_project
             at src/templates/handler.rs:36
  27: quickproj::client::Client::init_project
             at src/client.rs:76
  28: quickproj::client::Client::run
             at src/client.rs:42
  29: quickproj::main
             at src/main.rs:19
  30: std::rt::lang_start::{{closure}}
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/rt.rs:64
  31: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:49
  32: std::panicking::try::do_call
             at src/libstd/panicking.rs:296
  33: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:82
  34: std::panicking::try
             at src/libstd/panicking.rs:275
  35: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  36: std::rt::lang_start_internal
             at src/libstd/rt.rs:48
  37: std::rt::lang_start
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/rt.rs:64
```
