### ISSUE TITLE
Examples crash

### ISSUE THREAD

**Issue by tailhook** [sunng87/handlebars-rust#91]
I'm trying to run examples in the library and `partials` work fine, but `render` and `render_file` do crash with the following backtrace:
```
     Running `target/debug/examples/render`
thread '<main>' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:325
stack backtrace:
   1:     0x558c84eac70f - std::sys::backtrace::tracing::imp::write::h3800f45f421043b8
   2:     0x558c84eaf40b - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::h0ef6c8db532f55dc
   3:     0x558c84eaf093 - std::panicking::default_hook::hf3839060ccbb8764
   4:     0x558c84ea5d3d - std::panicking::rust_panic_with_hook::h5dd7da6bb3d06020
   5:     0x558c84eaf651 - std::panicking::begin_panic::h9bf160aee246b9f6
   6:     0x558c84ea6cba - std::panicking::begin_panic_fmt::haf08a9a70a097ee1
   7:     0x558c84eaf5ee - rust_begin_unwind
   8:     0x558c84ee517f - core::panicking::panic_fmt::h93df64e7370b5253
   9:     0x558c84ee5458 - core::panicking::panic::h9d5bd65bbb401959
  10:     0x558c84cc4982 - _<std..option..Option<T>>::unwrap::h1d2386177dc008f1
                        at ../src/libcore/macros.rs:21
  11:     0x558c84cc42e6 - render::rank_helper::hb4e197b8830cc302
                        at examples/render.rs:36
  12:     0x558c84cd0748 - fn(&handlebars..Context, &handlebars..Helper<'_>, &handlebars..Registry, &mut handlebars..RenderContext<'_>) .> std..
result..Result<(), handlebars..RenderError> $u7b$rank_helper$u7d$::fn_pointer_shim.12163::hff212c1b973e2bff
  13:     0x558c84cd071b - _<F as handlebars..HelperDef>::call::h34ade6fc4b16b78b
                        at src/helpers/mod.rs:36
  14:     0x558c84d4ecb3 - _<template..TemplateElement as render..Renderable>::render::h4d6ca29b82b9f52c
                        at src/render.rs:446
  15:     0x558c84d3519f - _<template..Template as render..Renderable>::render::hbda4631c4cc78527
                        at src/render.rs:394
  16:     0x558c84d0f180 - _<helpers..helper_each..EachHelper as helpers..HelperDef>::call::h69f04b59ea7c3464
                        at src/helpers/helper_each.rs:51
```

**Comment by sunng87** [comment]
Thank you @tailhook , this is due to a recent update on path visitor. I have updated the template and it works now. Please update the repo.

**Comment by tailhook** [comment]
It works now. Thanks!
